#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: micro-ecom-user
#          uri: lb://MICRO-ECOM-USER
#          predicates:
#            - Path=/users/**
#          filters:
#              - "RewritePath=/users(?<segment>/?.*),/api/users${segment}"
#        - id: micro-ecom-service
#          uri: lb://MICRO-ECOM-SERVICE
#          predicates:
#            - Path=products/**
#          filters:
#            - "RewritePath=/products(?<segment>/?.*),/api/product${segment}"
#        - id: micro-ecom-order
#          uri: lb://MICRO-ECOM-ORDER
#          predicates:
#            - Path=orders/**, /api/cart/**
#          filters:
#            - "RewritePath=/orders(?<segment>/?.*),/api/orders${segment}"
#        - id: eureka
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/main
#          filters:
#            - "RewritePath=(?<segment>/?.*),/api/${segment}"
#        - id: eureka-server-static
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eurela/**

server:
  port: 8010

#logging:
#  level:
#    root: info
#    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
#    org.springframework.cloud.gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      ecomBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based


# SECURITY
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://keycloak:8001/realms/ecom-micro