spring:
  application:
    name: configdemo
  config:
    import: configserver:http://localhost:8099
  profiles:
    active: prod

build:
  id: ${ID}
  version: ${VERSION}
  name: ${NAME}
server:
  port: 8088

management:
  endpoint:
    web:
      exposure:
        include: refresh

#BUILD_ID=;BUILD_NAME=;BUILD_VERSION=1.1.1