spring:
  application:
    name: provider
server:
  port: 2222
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka
    register-with-eureka: true
    fetch-registry: true
